### PR TITLE
Add QR code widget (#59)

### PR DESCRIPTION
**Pull request by vollkorntomate**
I created a Widget Extension (>= iOS 14), which shows the user's certificate that is currently in use. It supports all three widget sizes (small, medium, large). The small size is still large enough to be scanned by the CovPassCheck app. I proposed this feature a couple of weeks ago in issue #59.

This feature enhances user experience, since users don't need to open the app anymore to show their COVID certificate. It even works from the lock screen, so users don't need to unlock their phones.

It also doesn't show any additional personal information like name, date of birth or certificate type.

The necessary translations are added by [this PR](https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/133).

Here are two screenshots of how the widget looks like (Xcode Preview):
Bildschirmfoto 2021-11-14 um 21 54 30
Bildschirmfoto 2021-11-14 um 21 54 41

### CODE REVIEW

**Comment by alexcimander** [comment]
Hey vollkorntomate,

thank you for this awesome extension - the team really loves it and appreciates your work! We will take it to the clients for further discussions and reviews. We will keep you updated in this thread.

thank you!

**Comment by vollkorntomate** [comment]
Hey @alexcimander,
I'm glad you like it. Are there any updates on this yet?

**Comment by JilAuraya** [comment]
Hi vollkorntomate, 
also from my side, amazing work! Thank you! 
Next week it will be presented. Of course, we also have to look towards Android since both OS need to be aligned. As soon as we have a decision we will let you know :)

**Comment by Ein-Tim** [comment]
@JilAuraya 

Do you have any update available here?

**Comment by Ein-Tim** [comment]
@timokoenig @alexcimander Maybe you can shine a light on the Staus of this PR?

**Comment by timokoenig** [comment]
@Ein-Tim I do not know the status. @JilAuraya or @alexcimander should know more 🙏

**Comment by JilAuraya** [comment]
@Ein-Tim Hi Tim, I apologize for the late response. At current times the focus of the stakeholders is on different topics than on the widget. Nevertheless, we still plead for its integration, but we need to bring it up again when times are a bit calmer. (And of course, we would ever need an Android equivalent from the community or scope it into the Android team.) As soon as I have news I will let you know of course. (And again, sorry for the delay!)

**Comment by Ein-Tim** [comment]
@vollkorntomate

It seems like the CovPass-Team, or rather the stakeholders, are not accepting this PR at the moment.
Maybe you would like to think about providing this PR to the cwa-app-iOS reposiotry.

**Comment by vollkorntomate** [comment]
Hi @Ein-Tim, thanks for your suggestion!
I looked into it, but it seems that the integration into the CWA is harder, mostly due to iOS's separation of the widget as a separate target.
In CovPass, all of the certificate storing is done in the `CovPassCommon` package which can simply be included in the target's dependencies. The CWA, however, has all of this logic in the main app, so each dependency of the `HealthCertificateService` (and their dependencies and so on) would need to be assigned a target membership of the widget extension in order for the build to succeed.

I might also be missing something here and it might in fact be much easier than this.

**Comment by Ein-Tim** [comment]
@vollkorntomate 

Ah, I understand. I sadly do not have enough knowledge to judge on this (@timokoenig) might, but seeing this (great) PR being stalled for more than 5 months is really sad, so I wanted to share my thoughts here.

**Comment by timokoenig** [comment]
@vollkorntomate I'm not very familiar with the CWA codebase and would need to look it up as well. The CWA community and repositories are very active so I guess if you ask there they might point you in the right direction and help you out.

I share the same thoughts as @Ein-Tim and would've loved to see that feature in CovPass but we can't do much here

**Pull request closed without merging**
